### Test project exist dubbo interface
DUBBO dubbo://10.255.0.1:31299
Content-Type: application/json
Interface: org.javamaster.service.washing.admin.api.dubbo.ServiceExchangeDubboService
Method: getExchangeInfo
Version: 1.0.0

{
  "reqDto": {
    "shippingExpressCodes":["20241024hd"]
  }
}

// Registry Description: This header indicates the configuration of the registration center,
// specifying this header will ignore the address on the url and obtain services from the registration center
### Test project not exist dubbo interface
DUBBO dubbo://dubbo.javamaster.org:31299
Content-Type: application/json
Interface-Name: org.javamaster.api.serviceorder.dubbo.IMHServiceOrderDubboService
Method: getOrderList
Version: 1.0.0
Registry: zookeeper://zk.javamaster.org:2181
Arg0-Type: org.javamaster.api.serviceorder.dto.GetOrderListDto

{
  "Arg0-Type": {
    "shopOrderId": "602495678454930066"
  }
}