### With header
GET https://www.baidu.com
Accept: application/json

### Url with param
GET https://www.baidu.com?show_env=1
Accept: application/json

### Reference variable
GET {{host}}/get?show_env={{show_env}}
Accept: application/json

### With cookie
GET https://www.baidu.com
Cookie: uid=123456789

### With builtin variable
GET https://www.baidu.com?id={{$uuid}}&ts={{$timestamp}}