@host = https://baike.baidu.com
@show_env = true

### With header
GET https://www.baidu.com
Accept: text/html

### Url with param
GET https://www.baidu.com?show_env=1
Accept: text/html

### Reference variable
GET {{host}}/lemma/api/home/module?show_env={{show_env}}
Accept: application/json

### With cookie
GET https://www.baidu.com
Cookie: uid=123456789

### With builtin variable
GET https://www.baidu.com?id={{$uuid}}&ts={{$timestamp}}

### path mulitline query param
GET https://www.baidu.com?
    firstname=John&
    lastname=Doe&
    town=Freetown