### mock server1
MOCK_SERVER http://localhost
Content-Type: application/json

{
  "title": "{{$random.university}}",
  "time": {{$timestamp}}
}

### mock server2
# @responseStatus 201
MOCK_SERVER http://localhost:8080
Content-Type: application/json
Message-ID: {{$random.alphanumeric(32)}}

{
  "title": "{{$random.book.title}}",
  "time": "{{$datetime}}"
}

### mock server3
# @staticFolder D:\
MOCK_SERVER http://localhost