### 带有json入参
POST https://miao.baidu.com/abdr
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### 请求体内引用内置方法和内置变量
POST https://miao.baidu.com/abdr
Content-Type: application/json

{
  "uuid": "{{$random.uuid}}",
  "desc": "{{$random.alphabetic(10)}}",
  "desc1": "{{$random.alphanumeric(10)}}",
  "desc2": "{{$random.numeric(10)}}",
  "base64": "{{$imageToBase64(E:\\image\\test.jpg)}}",
  "value": "content",
  "ts": "{{$timestamp}}",
  "price2": {{$randomInt}}
}

### 复杂multipart请求
# @connectTimeout 6
# @readTimeout 6
POST https://miao.baidu.com/abdr
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="first"; filename="input.txt"

< ./input.txt
--boundary
Content-Disposition: form-data; name="second"; filename="input-second.txt"

Text
--boundary
Content-Disposition: form-data; name="third";

< ./input.txt
--boundary--