### with json param
POST https://miao.baidu.com/abdr
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Request body with builtin methods and builtin variables
POST https://miao.baidu.com/abdr
Content-Type: application/json

{
  "uuid": "{{$random.uuid}}",
  "desc": "{{$random.alphabetic(10)}}",
  "desc1": "{{$random.alphanumeric(10)}}",
  "desc2": "{{$random.numeric(10)}}",
  "base64": "{{$imageToBase64('E:\\image\\test.jpg')}}",
  "value": "content",
  "ts": "{{$timestamp}}",
  "price2": {{$randomInt}}
}

### Complex multipart request
# @connectTimeout 6
# @readTimeout 6
POST https://miao.baidu.com/abdr
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="first"; filename="input.txt"
Content-Type: text/plain

< ./input.txt
--boundary
Content-Disposition: form-data; name="second"; filename="input-second.txt"
Content-Type: text/plain

This is text
--boundary
Content-Disposition: form-data; name="third"
Content-Type: application/x-www-form-urlencoded

name=yu&age=23
--boundary
Content-Disposition: form-data; name="forth"
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}
--boundary--