// Introduce javascript library with use npm url, it will be download and cache.
// You can find the npm download url in package-lock.json
// 使用 npm 链接引入 js库, 将会被下载和缓存, npm 链接可以在 package-lock.json 文件中找到
# @require https://registry.npmmirror.com/moment/-/moment-2.30.1.tgz
# @require https://registry.npmmirror.com/lodash/-/lodash-4.17.21.tgz
# @require https://registry.npmmirror.com/crypto-js/-/crypto-js-3.3.0.tgz

// Global import local js file 全局导入本地 js 文件
# @import public.js

<! {%
    // Global js previous handler 全局js前置处理器
    console.log("Call moment format:", moment().format())

    client.global.set('globalName', 'jufeng98');
    request.variables.set('requestName', 'jufeng9878');

    // Set request header 设置请求头
    request.headers.set('My-Header', request.environment.get("token"));

    // Append request header 追加请求头
    request.headers.add('Set-Cookie', request.environment.get("token1"));
    request.headers.add('Set-Cookie', request.environment.get("token2"));

    const secret = "RHDcnjfmkES"
    const signSource = secret + request.body.tryGetSubstituted() + secret;

    // Use npm js library 使用 npm js库依赖
    const signTmp = CryptoJS.MD5(signSource).toString()
    console.log("md5(calculate by js):", signTmp);

    const params = new URLSearchParams();
    params.append("name", "yu");
    console.log("query param:", params.toString());

    // Execute local js file 执行本地 js 文件
    const global = require('myUtils.js');
    const res = global.MyUtils.isBlank('hello');
    client.log(`result: ${res}`);

%}

// file variables 文件变量
@tokenAdmin={{$random.uuid}}
@name=jufeng

### use variable
< {%
    // Use builtin crypto object 使用内置的 crypto 对象
    const sign = crypto.md5().updateWithText(signSource).digest().toHex();
    request.variables.set('sign', sign);
    console.log("md5(calculate by java):", sign);

    // pre-request js handler 预请求js前置处理器
    request.variables.set('cnName', 'jufeng987878');
    console.log("Call lodash capitalize:", _.capitalize('FRED'))
%}
POST https://baike.baidu.com/api/activity/resource?a={{globalName}}&b={{requestName}}&sign={{sign}}
Content-Type: application/json
Admin-Token: {{tokenAdmin}}
Name: {{name}}
Cn-Name: {{cnName}}

{
  "desc": "hello"
}

> {%
    client.global.set("errmsg", response.body.errmsg);
    console.log("Call lodash capitalize:", _.capitalize('JACK'))
%}

>> {{$historyFolder}}/result.json

### Constructing Hash from request body with crypto
< {%
    const hash = crypto.sha256()
        .updateWithText(request.body.tryGetSubstituted())
        .digest().toHex();
    request.variables.set("hash", hash)
%}
POST https://baike.baidu.com/api/activity/resource
X-My-Hash: {{hash}}
Content-Type: application/json

{
  "prop": "value"
}

### Constructing HMAC from request body with crypto
< {%
    const signature = crypto.hmac.sha256()
        // get variable from http-client.private.env.json
        .withTextSecret(request.environment.get("secret") || 'RHDcnjfmkES')
        .updateWithText(request.body.tryGetSubstituted())
        .digest().toHex();
    request.variables.set("signature", signature)
%}
POST https://baike.baidu.com/api/activity/resource
X-My-Signature: {{signature}}
Content-Type: application/json

{
  "prop": "value"
}

### post js handler
GET https://baike.baidu.com/api/activity/resource

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, "Response status is not 200");
        client.log('content-type:' + response.contentType.mimeType)

        const result = jsonPath(response.body, "$.errno");
        console.log(result);
    })
%}

### Check response body
GET https://baike.baidu.com/api/activity/resource

> {%
    client.test("Headers option exists", () => {
        client.assert(response.body.hasOwnProperty("errno"), "Cannot find 'errno' option in response");
    })
%}

### Check Content-Type from headers
GET https://baike.baidu.com/api/activity/resource

> {%
    client.test("Content-Type is application/json", () => {
        const mimeType = response.contentType.mimeType;
        client.assert(mimeType === 'application/json', `Expected Content-Type is application/json, but actual is  ${mimeType}`);
    })
%}

### Operate xml
GET https://examples.http-client.intellij.net/xml

> {%
    const slide = response.body.getElementsByTagName("slide").item(0).textContent
    client.log("textContent:", slide)

    const result = xpath(response.body, "/slideshow/slide/title")
    console.log("xPath result:", result)
%}

### Tip: clear global variables before the request
< {%
    client.global.clearAll()
    client.global.set("my-variable", "I will not be deleted!")
%}
POST https://baike.baidu.com/api/activity/resource
Content-Type: application/json

{
    "my-variable": "{{my-variable}}"
}