@username = jufeng98

### with Authorization
GET https://www.baidu.com
Authorization: Basic user passwd

### header with builtin variables
< {%
    request.variables.set('password', '123456');
%}
GET https://www.baidu.com
Authorization: Basic {{username}} {{password}}

### with token json param
POST https://chat.baidu.com/aichat/api/messages/list
Content-Type: application/json

{
  "type": "starMap",
  "ids": [
    "260181"
  ]
}

> {%
    client.global.set("auth_token", response.body.logid);
%}

### Use token
POST https://baike.baidu.com/api/activity/resource?tk=fda90026557974f384a8e5f687d13edb
Content-Type: application/json

{
  "token": "{{auth_token}}"
}