### with Authorization
GET https://www.baidu.com
Authorization: Basic user passwd

### header with builtin variables
GET https://www.baidu.com
Authorization: Basic {{username}} {{password}}

### with token json param
POST https://miao.baidu.com/abdr
Content-Type: application/json

{
  "token": "my-secret-token"
}